add_newline = false

[character]
success_symbol = "[I](bold green) "
error_symbol =   "[I](bold red) "
vicmd_symbol =   "[N](bold green) "

[directory]
style = "bold blue"
truncate_to_repo = true

[golang]
symbol = "G "

[python]
symbol = "P "

